title: "💎 Gemma Garage"
description: "Google Summer of Code (GSoC) 2025 @ Google DeepMind"

# Use remote_theme instead of theme
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

author:
  name: "Lucas Martins"
  bio: "Google Summer of Code 2025 @ DeepMind | Gemma Garage Lead"
